### ISSUE TITLE
Verify and clean up data scaling configuration

### ISSUE THREAD

**Issue by rengelke** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#112]
Review where data scaling (lin, log) is configured and applied. Eventually migrate transformation to calculateCostMetrics.

**Comment by PavelBal** [comment]
Here 
https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/blob/6250c87e2bce0ea63e39538f99940eb8fe6a92bb/R/ParameterIdentification.R#L263
and here
https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/blob/6250c87e2bce0ea63e39538f99940eb8fe6a92bb/R/ParameterIdentification.R#L274
