### ISSUE TITLE
Add build packages to the release assets

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#126]
Please add the latest (binary and source) builds to the release.

**Comment by rengelke** [comment]
[x] updated the v2.0.0 release with the new source and binary builds [v.2.0.0](https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/releases/tag/v2.0.0)
[x] tested installation 
[x] all tests passed

**Comment by PavelBal** [comment]
Nice.
