### ISSUE TITLE
Use `ospsuite.utils::validateIsOption`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#129]
Remove the same function from this package.

**Comment by rengelke** [comment]
I planned to wait until the function is merged into main in ospsuite.utils before deprecating it here.

**Comment by PavelBal** [comment]
We already require the non-released version of ospsiuite-r, so it is okay to use the develop branch of the utils.

But yes, in the future we will have to re-think the process. The main branch of the utils package is not being updated as often as our packages.

And also just remove the function from here without deprecating.
