### ISSUE TITLE
PIOutputMapping - scaling field

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#38]
- [x] Add check for only supported values (log and lin)
- [x] Improve description - what implications does it have? Calculation of residuals, plotting of current results... Refer to the article.

**Comment by PavelBal** [comment]
This is implemented now?

**Comment by rengelke** [comment]
There is no validation in place yet.

 Is there a particular reason why this setting is within PIOutputMappings and not e.g. PIConfiguration?

**Comment by PavelBal** [comment]
> Is there a particular reason why this setting is within PIOutputMappings and not e.g. PIConfiguration?
Yes, different scaling options may apply to different output mappings.
