### ISSUE TITLE
Rename `PIConfiguration:targetFunction` to `objectiveFunction`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#80]

**Comment by PavelBal** [comment]
Field `targetFunctionType` to `objectiveFunction`. Or `errorModel`?

**Comment by rengelke** [comment]
objectiveFunction sounds good. Adapted in commit 413fde53

**Comment by rengelke** [comment]
objectiveFunction sounds good. Adapted in commit413fde53

**Comment by PavelBal** [comment]
@rengelke Please only close issues when the respective PR is already merged into `develop` or `main`.
