### ISSUE TITLE
Set up GitHub actions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#95]
To build the package and the website instead of using AppVeyor.

See esqlabsR for reference.

**Comment by Felixmil** [comment]
Let's use this occasion to refactor esqlabsR actions to a dedicated repository. All OSPS repositories will be able to reuse these actions and we'll have to maintain core logic in one place.

**Comment by PavelBal** [comment]
Yuri created something here:
https://github.com/Open-Systems-Pharmacology/Workflows/pull/18

**Comment by Yuri05** [comment]
> Let's use this occasion to refactor esqlabsR actions to a dedicated repository. All OSPS repositories will be able to reuse these actions and we'll have to maintain core logic only in one place.

Good idea. We have the https://github.com/Open-Systems-Pharmacology/Workflows for the "global" reusable tasks

> Yuri created something here: [Open-Systems-Pharmacology/Workflows#18](https://github.com/Open-Systems-Pharmacology/Workflows/pull/18)

Here I extracted the "build website" GH-action by @pchelle into a reusable workflow. 
To use it with ospsuite-R etc. the workflow could be extended with an optional installation step, which would e.g. install PK-Sim etc. E.g. we could pass an optional _UserDefinedInstallation.R_ to the workflow:
```
...
on: 
  workflow_call:
    inputs:
      ...
      user-defined-installation-script:
        required: false
        type: string
        default: 'UserDefinedInstallation.R'
...

- name: User defined installation
  run: |
      if [ -f ${{ inputs.user-defined-installation-script }} ]; then
          Rscript ${{ inputs.user-defined-installation-script }}
      fi
...
```

**Comment by Yuri05** [comment]
Some other actions, which are currently used in different R-repos and could be transferred to global:
* Package check: https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/blob/develop/.github/workflows/check-full.yaml
* (Nightly) Code coverage: https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/.github/workflows/codecov-nightly.yml
* Lint: https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/.github/workflows/lint.yaml
* ... (maybe more)

**Comment by Yuri05** [comment]
> To build the package and the website instead of using AppVeyor.

Question: when you build the package via a GH-action and not via AppVeyor - where do you upload the package artifacts?

**Comment by Felixmil** [comment]
It is uploaded automatically by the action at the end and is available as run artifact:
https://github.com/esqLABS/esqlabsR/actions/runs/7570017160


We also have a permanent link that target the latest build of main branch: https://nightly.link/esqLABS/esqlabsR/workflows/R-CMD-check.yaml/main/built_package.zip

FYI we already have in esqlabsR repo:
- RCMD Check + package build
- Tests
- codecov
- Website build

**Comment by Yuri05** [comment]
@Felixmil Thx for the info :)
After the next OSP release (V12) and after the next RE release we should try to consolidate all those actions.
Then we could create a **template repo for new R packages** on the OSP
@pchelle @msevestre @KatrinCoboeken
